# Оценка надежности заданий с примением формулы Спирмена-Брауна для демоварианта олимпиады по анализу данных

## Подготовка данных

In [1]:
import numpy as np
import pandas as pd

Взглянем на наш датасет:

In [2]:
df = pd.read_excel('answers_default.xlsx')
df.head()

Отметка времени      Адрес электронной почты  Баллы  \
0 2021-06-12 23:19:06.766   micro.fascinated@gmail.com   72.0   
1 2021-06-15 22:41:14.609  egorpranikov39562@gmail.com    0.0   
2 2021-06-16 17:33:05.947                utygo@mail.ru    3.0   
3 2021-06-16 18:04:25.451     danya.palatkin@yandex.ru    3.0   
4 2021-06-16 19:35:15.827   catya.mentyukova@yandex.ru   23.0   

     ExtendedForms Id (skip this field) Укажите ваш класс  \
0  93a8ba0a-dc8d-4389-851e-66f3474a1ab9                10   
1  93aeb644-3242-4cce-839d-7872dea3ad0b                 9   
2  93b03888-8a36-49d3-b75d-1b94968305ac                 9   
3  93b038a5-2dbc-4f2b-9076-fca1f75d3564                 9   
4  93b07103-f970-4192-bb90-bfecea94b906                11   

  1. Имеется пять действительных чисел: N,9,5,4,7. При каких значениях N из предложенных медиана будет равна среднему?  \
0                                      10,  6,25,  0                                                                     
1                                           6,25,  9                                                                     
2                                       0,  6,25,  9                                                                     
3                                       0,  6,25,  9                                                                     
4                                      10,  6,25,  0                                                                     

  2. Измерен рост 25 человек, рост каждого человека оказался отличным от других. Средний рост оказался равным 160 см. Медиана оказалась равной 155 см. Васин рост в 163 см был ошибочно внесен как 173 см. Как изменится величина среднего роста после исправления ошибки?  \
0                                         Увеличится                                                                                                                                                                                                                         
1                                         Увеличится                                                                                                                                                                                                                         
2           Может как увеличиться, так и уменьшиться                                                                                                                                                                                                                         
3           Может как увеличиться, так и уменьшиться                                                                                                                                                                                                                         
4                                         Уменьшится                                                                                                                                                                                                                         

  3. Перед вами таблица из демографического отчета города N о количестве детей в семьях. Все семьи города N имеют двух родителей, а все дети проживают со своими родителями. Выберите все верные утверждения, которые можно сделать на основе представленной таблицы.  \
0  Медианное количество детей в семье - 2 ребенка...                                                                                                                                                                                                                    
1                                               None                                                                                                                                                                                                                    
2  Среднее количество детей в семье меньше медиан...                                                   

Изменим названия колонок (сделаем их названия короче, в колонках заданий уберем условия)

In [3]:
df.columns = range(-4,27)
df.rename(columns={-4: 'time of ending', -3: 'email', -2:'total score', -1:'id', 0:'education'}, inplace=True)
df.tail()

time of ending                       email  total score  \
13 2021-06-18 11:06:39.326        loamelina@edu.hse.ru          5.0   
14 2021-06-18 12:02:39.807     myubelozerov@edu.hse.ru         11.0   
15 2021-06-18 17:45:05.895          nosmasha@gmail.com          4.0   
16                     NaT                         NaN          NaN   
17 2021-06-20 12:38:35.424  m.stolyaroff2014@yandex.ru         25.0   

                                      id          education              1  \
13  93b3c663-b5db-40b4-b0a1-d04d146a6b6e  Студент/студентка  10,  6,25,  0   
14  93b3c86b-9ff8-434e-ae1f-8c4b3eddaba6  Студент/студентка  10,  6,25,  0   
15  93b43249-eda2-490f-895b-499edda23039  Студент/студентка  10,  6,25,  0   
16                                  None               None           None   
17  93b7edac-675a-4a66-a4d6-597ec0b56279  Студент/студентка  10,  6,25,  0   

                2                                                  3  \
13  Не уменьшится  Среднее количество детей в семье меньше медиан...   
14     Уменьшится  Медианное количество детей в семье - 2 ребенка...   
15     Уменьшится  Среднее количество детей в семье меньше медиан...   
16           None                                               None   
17     Уменьшится  Медианное количество детей в семье - 2 ребенка...   

                                                    4     5  ...   17  \
13  Более половины опрошенных поддерживает кандида...  16.0  ...  2.0   
14  Среднее значение опрошенных, поддерживающих ка...  32.0  ...  1.0   
15  Более половины опрошенных поддерживает кандида...  32.0  ...  NaN   
16                                               None   NaN  ...  NaN   
17  Среднее значение опрошенных, поддерживающих ка...  32.0  ...  1.0   

                  18      19  \
13  только (2) и (3)     4.8   
14        только (3)  5, 5,2   
15              None    None   
16              None    None   
17        только (3)  5, 5,2   

                                                   20  \
13  Исходя из двух графиков, можно сделать вывод о...   
14  Исходя из двух графиков, можно сделать вывод о...   
15                                               None   
16                                               None   
17  Исходя из двух графиков, можно сделать вывод о...   

                                                   21  \
13  Медианное значение выбросов в Великобритании в...   
14  В США наблюдается тренд на снижение количества...   
15                                               None   
16                                               None   
17  Медианное значение выбросов в Великобритании в...   

                                                   22  \
13  Самый высокий показатель трудоустройства не оз...   
14  Исландия - самая привлекательная страна для ми...   
15                                               None   
16                                               None   
17  В развитых странах ситуация с трудоустройством...   

                                                   23  \
13  И по результатам оценки уровня читательской гр...   
14  И по результатам оценки уровня читательской гр...   
15                                               None   
16                                               None   
17  Разброс результатов тестирования между полами ...   

                                      24      25  \
13              Третий квартиль равен 11  10, 10   
14  Данное распределение - одномодальное   3, 17   
15                                  None    None   
16                                  None    None   
17              Третий квартиль равен 11   13, 7   

                                                   26  
13  Линейная линия тренда выборки, представляющей ...  
14  Выборка, состоящая из 2-х наблюдений, не может...  
15                                               None  
16                                               None  
17                             Нет верных утверждений  

[5 rows x 31 columns]

Стало выглядеть поприятнее.

Последним тест проходил я, мои ответы на задания являются верными. Поэтому возьмем их за маркер верных ответов и изменим значения в колонках заданий, чтобы ответы участников представлялись бинарным способом (1 - в случае верного ответа, 0 - в случае неверного):

In [4]:
scores = (df[range(1, 27)] == df.iloc[17][range(1, 27)]) * 1 

In [5]:
df.drop(range(1, 27), axis='columns', inplace=True)
df1 = pd.concat([df, scores], axis=1)
df1.head()

time of ending                        email  total score  \
0 2021-06-12 23:19:06.766   micro.fascinated@gmail.com         72.0   
1 2021-06-15 22:41:14.609  egorpranikov39562@gmail.com          0.0   
2 2021-06-16 17:33:05.947                utygo@mail.ru          3.0   
3 2021-06-16 18:04:25.451     danya.palatkin@yandex.ru          3.0   
4 2021-06-16 19:35:15.827   catya.mentyukova@yandex.ru         23.0   

                                     id education  1  2  3  4  5  ...  17  18  \
0  93a8ba0a-dc8d-4389-851e-66f3474a1ab9        10  1  0  0  0  1  ...   1   1   
1  93aeb644-3242-4cce-839d-7872dea3ad0b         9  0  0  0  0  0  ...   0   0   
2  93b03888-8a36-49d3-b75d-1b94968305ac         9  0  0  0  0  1  ...   0   0   
3  93b038a5-2dbc-4f2b-9076-fca1f75d3564         9  0  0  0  0  0  ...   1   0   
4  93b07103-f970-4192-bb90-bfecea94b906        11  1  1  0  1  0  ...   1   1   

   19  20  21  22  23  24  25  26  
0   0   0   1   0   1   1   1   1  
1   0   0   0   0   0   0   0   0  
2   0   0   0   0   0   1   1   0  
3   0   0   0   0   0   0   0   0  
4   0   0   1   1   1   1   0   1  

[5 rows x 31 columns]

Итоговый балл каждого испытуемого перезапишем с учетом (потому что в форме были неправильные ответы):

In [6]:
df1['total score'] = np.sum(np.array(df1[range(1, 27)]), axis=1)
df1.head()

time of ending                        email  total score  \
0 2021-06-12 23:19:06.766   micro.fascinated@gmail.com           17   
1 2021-06-15 22:41:14.609  egorpranikov39562@gmail.com            0   
2 2021-06-16 17:33:05.947                utygo@mail.ru            3   
3 2021-06-16 18:04:25.451     danya.palatkin@yandex.ru            3   
4 2021-06-16 19:35:15.827   catya.mentyukova@yandex.ru           21   

                                     id education  1  2  3  4  5  ...  17  18  \
0  93a8ba0a-dc8d-4389-851e-66f3474a1ab9        10  1  0  0  0  1  ...   1   1   
1  93aeb644-3242-4cce-839d-7872dea3ad0b         9  0  0  0  0  0  ...   0   0   
2  93b03888-8a36-49d3-b75d-1b94968305ac         9  0  0  0  0  1  ...   0   0   
3  93b038a5-2dbc-4f2b-9076-fca1f75d3564         9  0  0  0  0  0  ...   1   0   
4  93b07103-f970-4192-bb90-bfecea94b906        11  1  1  0  1  0  ...   1   1   

   19  20  21  22  23  24  25  26  
0   0   0   1   0   1   1   1   1  
1   0   0   0   0   0   0   0   0  
2   0   0   0   0   0   1   1   0  
3   0   0   0   0   0   0   0   0  
4   0   0   1   1   1   1   0   1  

[5 rows x 31 columns]

Наконец, избавимся от лишних столбцов (окончания прохождения тестирования, индекса и почты), так как эта информация не пригодится нам для анализа и участников, соответствующих строкам 0, 16, 17, потому что они являлись командой разработчиков тестирования проверяющей корректность работы составленной формы.

In [7]:
df1.drop(['email', 'id', 'time of ending'], axis='columns', inplace=True)
df1.drop([17, 16, 0], axis='index', inplace=True)
df1.head()

total score education  1  2  3  4  5  6  7  8  ...  17  18  19  20  21  22  \
1            0         9  0  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   
2            3         9  0  0  0  0  1  0  0  0  ...   0   0   0   0   0   0   
3            3         9  0  0  0  0  0  0  0  0  ...   1   0   0   0   0   0   
4           21        11  1  1  0  1  0  1  1  1  ...   1   1   0   0   1   1   
5            6         9  1  1  1  0  0  0  0  1  ...   1   0   0   0   0   0   

   23  24  25  26  
1   0   0   0   0  
2   0   1   1   0  
3   0   0   0   0  
4   1   1   0   1  
5   0   0   0   0  

[5 rows x 28 columns]

Немного изменим порядок столбцов для удобства восприятия.

In [8]:
df1['score'] = df1['total score']
df1.drop(['total score'], axis='columns', inplace=True)
df1.head()

education  1  2  3  4  5  6  7  8  9  ...  18  19  20  21  22  23  24  25  \
1         9  0  0  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   
2         9  0  0  0  0  1  0  0  0  0  ...   0   0   0   0   0   0   1   1   
3         9  0  0  0  0  0  0  0  0  1  ...   0   0   0   0   0   0   0   0   
4        11  1  1  0  1  0  1  1  1  1  ...   1   0   0   1   1   1   1   0   
5         9  1  1  1  0  0  0  0  1  0  ...   0   0   0   0   0   0   0   0   

   26  score  
1   0      0  
2   0      3  
3   0      3  
4   1     21  
5   0      6  

[5 rows x 28 columns]

Экспортируем файл:

In [9]:
df1.to_excel('Результаты тестирования.xlsx')

Теперь оставим лишь задания на множественный выбор:


In [10]:
solo_numbers = [1, 2, 5, 8, 9, 12, 14, 16, 17, 18, 21, 24, 25, 26]
data = df1.drop(solo_numbers, axis='columns')
data

education  3  4  6  7  10  11  13  15  19  20  22  23  score
1                   9  0  0  0  0   0   0   0   0   0   0   0   0      0
2                   9  0  0  0  0   0   0   0   0   0   0   0   0      3
3                   9  0  0  0  0   0   0   0   0   0   0   0   0      3
4                  11  0  1  1  1   1   1   1   1   0   0   1   1     21
5                   9  1  0  0  0   0   0   0   0   0   0   0   0      6
6                   9  1  0  0  1   0   0   0   0   0   0   0   0      9
7                   9  0  0  1  0   0   0   0   0   0   0   0   0      4
8                  11  1  0  0  0   0   0   0   0   1   0   0   0      9
9                  10  1  1  1  0   0   0   1   1   1   0   0   0     13
10                 11  0  0  0  0   0   0   0   0   0   0   0   0      5
11                 11  0  0  0  0   0   0   0   0   0   0   0   0      4
12                 11  1  1  0  1   0   0   1   0   0   0   0   0      9
13  Студент/студентка  0  0  0  0   0   0   0   0   0   0   0   0      4
14  Студент/студентка  0  1  1  0   0   0   0   0   1   0   0   0     12
15  Студент/студентка  0  0  1  0   0   0   0   0   0   0   0   0      4

In [11]:
#data.to_excel('Множ выбор результаты.xlsx')

## Оценка надежности с применением формулы Спирмена-Брауна

In [12]:
data.columns = range(14)
data.rename(columns={0: 'education', 13:'total score'}, inplace=True)
data

education  1  2  3  4  5  6  7  8  9  10  11  12  total score
1                   9  0  0  0  0  0  0  0  0  0   0   0   0            0
2                   9  0  0  0  0  0  0  0  0  0   0   0   0            3
3                   9  0  0  0  0  0  0  0  0  0   0   0   0            3
4                  11  0  1  1  1  1  1  1  1  0   0   1   1           21
5                   9  1  0  0  0  0  0  0  0  0   0   0   0            6
6                   9  1  0  0  1  0  0  0  0  0   0   0   0            9
7                   9  0  0  1  0  0  0  0  0  0   0   0   0            4
8                  11  1  0  0  0  0  0  0  0  1   0   0   0            9
9                  10  1  1  1  0  0  0  1  1  1   0   0   0           13
10                 11  0  0  0  0  0  0  0  0  0   0   0   0            5
11                 11  0  0  0  0  0  0  0  0  0   0   0   0            4
12                 11  1  1  0  1  0  0  1  0  0   0   0   0            9
13  Студент/студентка  0  0  0  0  0  0  0  0  0   0   0   0            4
14  Студент/студентка  0  1  1  0  0  0  0  0  1   0   0   0           12
15  Студент/студентка  0  0  1  0  0  0  0  0  0   0   0   0            4

Напомним, что для расчета корреляции используется следующих коэффициент:

$$r_{1/2} = \frac{n  \sum_{i=1}^n x_i y_i - \left( \sum_{i=1}^n x_i\right) \cdot \left( \sum_{i=1}^n y_i\right) }{\sqrt{\left( n\sum_{i=1}^n x_i^2 - \left(\sum_{i=1}^n x_i\right)^2 \right) \cdot \left( n\sum_{i=1}^n y_i^2 - \left(\sum_{i=1}^n y_i\right)^2 \right)}}$$

где $x_i$ и $y_i$ - баллы испуытуемого $i$ за нечетные и четные задания соответственно. То, что в тесте были задания с единственным верным вариантом ответа, которые мы не учитываем, по сути, не должно влиять на результат, так как задания были разбросаны в случайном порядке, что не должно было как-то особоенно повлиять на итоговый балл испытуемых. 

Для внесения большей ясности введем обозначим отдельные компоненты указанной выше формулы:
$$ r_{1/2} = \frac{A - B \cdot C }{\sqrt{\left( D - B^2 \right) \cdot \left( E - C^2 \right)}}$$

Рассчитаем компоненты:

In [13]:
scores = np.array(data[range(1, 13)])
X = np.sum(scores[:, ::2], axis=1)
Y = np.sum(scores[:, 1::2], axis=1)
n = len(X)
print(X)
print(Y)

[0 0 0 4 1 1 1 2 4 0 0 2 0 2 1]
[0 0 0 5 0 1 0 0 2 0 0 2 0 1 0]


In [14]:
A = n * X @ Y.T
B = np.sum(X)
C = np.sum(Y)
D = n * np.sum(X ** 2)
E = n * np.sum(Y ** 2)

r0 = (A - B * C) / np.sqrt((D - B ** 2) * (E - C ** 2))
r0

0.8175408780658805

Теперь сделаем корректировку показателя с помощью формулы Спирмена-Брауна:
$$ r_t = \frac{2r_{1/2}}{1 + r_{1/2}} $$

In [15]:
rt = 2 * r0 / (1 + r0)
rt

0.899612094486545

Полученный коэффициент является весьма высоким, что вызвано, скорее, выборкой, нежели качеством заданий. Несмотря на то, что показатель превышает пороговый (0,7), точный вывод о надежности составленной совокупности заданий для множественного выбора сделать нельзя. В представленнной для анализа выборке было мало наблюдений, cлишком много ответов участников были неправильными, из-за чего коэффициент корреляции получился довольно высоким (так как ноль коррелирует с нулем идеально).

Тем не менее, здесь представлен достаточно подробный и, надеюсь, понятный способ получения оценки надежности теста, который можно импользовать в более крупных исследованиях. А приведенные расчеты можно использовать в качестве ценного примера и напоминания, что получение благоприятных вычисленных показателей не всегда однозначно соответствует благоприятный результат.

## Другое

### Для тестов с едининственным верным варианта ответа

В исследовательских целях рассчитаем теперь коэффициент надежности для заданий с одним верным вариантом ответа.

In [16]:
multiple_numbers = [3, 4, 6, 7, 10, 11, 13, 15, 19, 20, 22, 23]
d1 = df1.drop(multiple_numbers, axis='columns')
d1.head()

education  1  2  5  8  9  12  14  16  17  18  21  24  25  26  score
1         9  0  0  0  0  0   0   0   0   0   0   0   0   0   0      0
2         9  0  0  1  0  0   0   0   0   0   0   0   1   1   0      3
3         9  0  0  0  0  1   1   0   0   1   0   0   0   0   0      3
4        11  1  1  0  1  1   1   1   1   1   1   1   1   0   1     21
5         9  1  1  0  1  0   1   0   0   1   0   0   0   0   0      6

In [17]:
d1.columns = range(16)
d1.rename(columns={0: 'education', 15:'total score'}, inplace=True)
d1.head()

education  1  2  3  4  5  6  7  8  9  10  11  12  13  14  total score
1         9  0  0  0  0  0  0  0  0  0   0   0   0   0   0            0
2         9  0  0  1  0  0  0  0  0  0   0   0   1   1   0            3
3         9  0  0  0  0  1  1  0  0  1   0   0   0   0   0            3
4        11  1  1  0  1  1  1  1  1  1   1   1   1   0   1           21
5         9  1  1  0  1  0  1  0  0  1   0   0   0   0   0            6

In [18]:
scores1 = np.array(d1[range(1, 15)])
X1 = np.sum(scores1[:, ::2], axis=1)
Y1 = np.sum(scores1[:, 1::2], axis=1)
n1 = len(X1)
print(X1)
print(Y1)

[0 2 2 5 2 3 1 2 4 1 1 2 3 4 2]
[0 1 1 7 3 4 2 5 3 4 3 3 1 5 1]


In [19]:
A = n1 * X1 @ Y1.T
B = np.sum(X1)
C = np.sum(Y1)
D = n1 * np.sum(X1 ** 2)
E = n1 * np.sum(Y1 ** 2)

r1= (A - B * C) / np.sqrt((D - B ** 2) * (E - C ** 2))
rt1 = 2 * r1 / (1 + r1)
rt1

0.749659619127491

Получилось, чо надежность тестов с одним верным вариантом ответа меньше. Но опять же, скорее всего, это связано с тем, что участникам тестирования было проще отвечать на такие вопросы, количество полученных нулей за эти задания меньше, по сравнению с вопросами на множественный выбор ответа

### Корреляция баллов участников за задания с одиночным и множественным выбором верного варианта ответа

In [20]:
X2 = X1 + Y1
Y2 = X + Y
n2 = len(X2)
Y2, X2

(array([0, 0, 0, 9, 1, 2, 1, 2, 6, 0, 0, 4, 0, 3, 1]),
 array([ 0,  3,  3, 12,  5,  7,  3,  7,  7,  5,  4,  5,  4,  9,  3]))

In [21]:
A = n2 * X2 @ Y2.T
B = np.sum(X2)
C = np.sum(Y2)
D = n2 * np.sum(X2 ** 2)
E = n2 * np.sum(Y2 ** 2)

r2 = (A - B * C) / np.sqrt((D - B ** 2) * (E - C ** 2))
r2

0.8087982784081824

In [22]:
2 * r2 / (1 + r2)

0.89429350753248

Коэффициент корреляции вновь получился высоким, что и должно было получаться из логики: если участник обладает достаточными знаниями, то он будет хорошо отвечать на задания обоих типов, и наоборот: если участник имеет плохие знания, то вряд ли его полученные низкие баллы за задания двух типов будут различаться. Но опять же стоит отметить, что в выборке многие участники получали нули, которые, вероятно, и влияют на столь большую величину показателя